sudo: false
language: android

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-24.0.1
    - android-23